### ISSUE TITLE
question,thanks for your help

### ISSUE THREAD

**Issue by lifuchao** [Jiramew/geetest_crack#2]
参考你的思路，我弄了个java测试类。
我现在的问题是：
（1）js里6132行是指的“U8Z = f2Z.V2Z()[0][34][10];”吗？我用的chrome F12,Pretty print看的，但是这行始终没有执行到，所以不太理解你的意思。
（2）你提供的方法输入参数str指的是哪个能指点下吗，你看我的cList和sString理解没错吧？
我搞这个，其实是想知道鼠标拖动的轨迹数组。谢谢了啊

public class TempTest {

    private static int[] cList=new int[]{12,58,98,36,43,95,62,15,12};//参数c
    private static String sString="515a366b";//参数s
    public static void main(String[] args)
    {
        System.out.printf(newFunc("6EFLJF?8(!)..!)!*!*!)!)!*!*!)!*!)(!!:((((()(ytwv*(y((ts()))(*())((!!($)6:9?9:9?9$,Td$)@S$*4A::8$,oC9_9S919:$0D"));
    }

    /**
     *  js line 6123
     *  @param str 输入str是什么
     *  @return
     */
    private static String newFunc(String str) {
        String m;
        int n = 0;
        String ss = str;
        int c0 = cList[0];
        int c2 = cList[2];
        int c4 = cList[4];
        for (int i = 0; i < 4; i++) {
            m = sString.substring(n, n + 2);
            n += 2;
            int k = Integer.parseInt(m, 16);
            String v = fromCharCode(k);
            int q = (c0 * k * k + c2 * k + c4) % str.length();
            ss = ss.substring(0, q) + v + ss.substring(q);
        }
        return ss;
    }

    //equal to js method fromCharCode
    public static String fromCharCode(int... codePoints) {
        return new String(codePoints, 0, codePoints.length);
    }
}

**Comment by Jiramew** [comment]
str指的是老版本中计算出的"a"参数，你的理解应该没有错误的~
啊~6132行指的是从那行之后加入了新的加密函数（如果那个文件没有变的话）。

**Comment by lifuchao** [comment]
@Jiramew 恩，明白了，我测试了ok，拿到aa了。我还想问下，它这个js是混淆了的吧，你是能反混淆了找到了这个方法的吗？另外，我想采集原始的轨迹（a加密之前就是原始轨迹，如何能找到，实在看不太懂那个js），能指点下吗？多谢了

**Comment by Jiramew** [comment]
我没有找到办法还原js>.<
调试大法好~我忘了那个轨迹出现在那块儿了，调试的时候肯定能看到的~[[a,b,c], [a,b,c], [a,b,c]......]~这样的二维~

**Comment by lifuchao** [comment]
@Jiramew 恩，还是多谢你啊，其实不用你这种方法，直接java调用它的js，就是那段也能直接得到aa。我现在破是破了，就是想采轨迹从而提高验证成功率

**Comment by Jiramew** [comment]
嗯嗯，直接调用js也是很好的方法~

**Comment by kongxu633** [comment]
function(Q4Y, P4Y) 坐标在这里

**Comment by lifuchao** [comment]
@Jiramew 恩，多谢了啊，已经成功采集轨迹入库了：）

**Comment by lifuchao** [comment]
@kongxu633 多谢多谢
